export const GET_ALL_LIST_AND_CARD_DOING = "GET_ALL_LIST_AND_CARD_DOING";
export const GET_ALL_LIST_AND_CARD_SUCCESS = "GET_ALL_LIST_AND_CARD_SUCCESS";
export const GET_ALL_LIST_AND_CARD_FALSE = "GET_ALL_LIST_AND_CARD_FALSE";

export const GET_LIST_AND_CARD_BY_ID_DOING = "GET_LIST_AND_CARD_BY_ID_DOING";
export const GET_LIST_AND_CARD_BY_ID_SUCCESS =
  "GET_LIST_AND_CARD_BY_ID_SUCCESS";
export const GET_LIST_AND_CARD_BY_ID_FALSE = "GET_LIST_AND_CARD_BY_ID_FALSE";

export const GET_ALL_LIST_DOING = "GET_ALL_LIST_DOING";
export const GET_ALL_LIST_SUCCESS = "GET_ALL_LIST_SUCCESS";
export const GET_ALL_LIST_FALSE = "GET_ALL_LIST_FALSE";

export const GET_LIST_BY_ID_DOING = "GET_LIST_BY_ID_DOING";
export const GET_LIST_BY_ID_SUCCESS = "GET_LIST_BY_ID_SUCCESS";
export const GET_LIST_BY_ID_FALSE = "GET_LIST_BY_ID_FALSE";

export const GET_ALL_CARD_DOING = "GET_ALL_CARD_DOING";
export const GET_ALL_CARD_SUCCESS = "GET_ALL_CARD_SUCCESS";
export const GET_ALL_CARD_FALSE = "GET_ALL_CARD_FALSE";

export const GET_CARD_BY_LIST_ID_DOING = "GET_CARD_BY_LIST_ID_DOING";
export const GET_CARD_BY_LIST_ID_SUCCESS = "GET_CARD_BY_LIST_ID_SUCCESS";
export const GET_CARD_BY_LIST_ID_FALSE = "GET_CARD_BY_LIST_ID_FALSE";

export const GET_CARD_BY_CARD_ID_DOING = "GET_CARD_BY_CARD_ID_DOING";
export const GET_CARD_BY_CARD_ID_SUCCESS = "GET_CARD_BY_CARD_ID_SUCCESS";
export const GET_CARD_BY_CARD_ID_FALSE = "GET_CARD_BY_ID_CARD_FALSE";

export const ADD_LIST_DOING = "ADD_LIST_DOING";
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS";
export const ADD_LIST_FALSE = "ADD_LIST_FALSE";

export const ADD_CARD_DOING = "ADD_CARD_DOING";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const ADD_CARD_FALSE = "ADD_CARD_FALSE";

export const EDIT_LIST_DOING = "EDIT_LIST_DOING";
export const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS";
export const EDIT_LIST_FALSE = "EDIT_LIST_FALSE";

export const EDIT_CARD_DOING = "EDIT_CARD_DOING";
export const EDIT_CARD_SUCCESS = "EDIT_CARD_SUCCESS";
export const EDIT_CARD_FALSE = "EDIT_CARD_FALSE";

export const UPDATE_CARD_DESCRIPTION_DOING = "UPDATE_CARD_DESCRIPTION_DOING";
export const UPDATE_CARD_DESCRIPTION_SUCCESS =
  "UPDATE_CARD_DESCRIPTION_SUCCESS";
export const UPDATE_CARD_DESCRIPTION_FALSE = "UPDATE_CARD_DESCRIPTION_FALSE";

export const DELETE_LIST_DOING = "DELETE_LIST_DOING";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const DELETE_LIST_FALSE = "DELETE_LIST_FALSE";

export const DELETE_CARD_DOING = "DELETE_CARD_DOING";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const DELETE_CARD_FALSE = "DELETE_CARD_FALSE";
